In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("results_qwen_eval.csv")

In [4]:
df2 = pd.read_csv("results_llama_eval_new.csv")

In [8]:
model_size = [0.5, 1.5, 14, 32, 3, 7, 0.5, 1.5, 14, 32, 3, 7]

In [9]:
df["model_size"] = model_size

In [ ]:
df = df.drop(columns=["output_dir", "fname", "split"])

In [15]:
df = df.sort_values(by='model_size')

In [5]:
model_size2 = [1, 3, 1, 3]

In [6]:
df2["model_size"] = model_size2

In [7]:
df2 = df2.drop(columns=["output_dir", "fname", "split"])
df2 = df2.sort_values(by='model_size')

In [8]:
df2

,dataset,method,model_name,model_size,n_samples,accuracy,injection_accuracy_match,injection_accuracy_entail,injection_accuracy_embed,injection_accuracy_llm,fluency,grammar,time
0,counterfact,in-context,Llama-3,1,1802,0.172031,0.180355,0.342397,0.035516,0.172031,0.009033,0.032608,0.513924
2,fewrel,in-context,Llama-3,1,2000,0.017000,0.072000,0.393500,0.017000,0.147500,0.001028,0.009543,0.575076
1,counterfact,in-context,Llama-3,3,1802,0.231964,0.655383,0.715871,0.449501,0.694784,-0.015593,-0.068667,0.551413
3,fewrel,in-context,Llama-3,3,2000,0.023500,0.321000,0.368000,0.093500,0.543500,0.002859,-0.003633,0.938960

In [29]:
df.drop(columns=["split"])

,dataset,method,model_name,model_size,n_samples,accuracy,injection_accuracy_match,injection_accuracy_entail,injection_accuracy_embed,injection_accuracy_llm,fluency,grammar,time
0,counterfact,in-context,Qwen2,0.5,1802,0.218091,0.856271,0.871809,0.452830,0.816315,-0.048269,0.704382,0.311996
6,fewrel,in-context,Qwen2,0.5,2000,0.022500,0.519500,0.445000,0.083500,0.650500,-0.079341,0.280558,0.710571
1,counterfact,in-context,Qwen2,1.5,1802,0.285794,0.917314,0.900111,0.031632,0.781909,-0.205205,0.165387,0.520367
7,fewrel,in-context,Qwen2,1.5,2000,0.043000,0.641500,0.479500,0.030000,0.739500,-0.242738,0.270034,1.039453
4,counterfact,in-context,Qwen2,3.0,1802,0.257492,0.899556,0.852941,0.039956,0.763041,-0.167822,0.429036,0.939725
10,fewrel,in-context,Qwen2,3.0,2000,0.043500,0.610000,0.515500,0.011500,0.685000,-0.092641,-0.034015,1.449315
5,counterfact,in-context,Qwen2,7.0,1802,0.431188,0.938402,0.822420,0.002775,0.736959,-0.166565,0.445500,0.879803
11,fewrel,in-context,Qwen2,7.0,2000,0.117000,0.560000,0.415500,0.001500,0.711000,-0.213053,0.221741,1.198106
2,counterfact,in-context,Qwen2,14.0,1802,0.411765,0.873474,0.787458,0.064928,0.706992,-0.151389,0.270904,1.440629
8,fewrel,in-context,Qwen2,14.0,2000,0.090000,0.567500,0.398000,0.048000,0.606500,-0.143740,0.126453,2.017387
3,counterfact,in-context,Qwen2,32.0,1802,0.477802,0.912875,0.832963,0.007769,0.718646,-0.172708,0.414613,2.230561
9,fewrel,in-context,Qwen2,32.0,1600,0.133125,0.566250,0.418125,0.003125,0.605000,-0.164819,0.079098,2.855275